### ISSUE TITLE
ch. 5 pag. 68 populates an array of all contacts (FAILED - 1)

### ISSUE THREAD

**Issue by romenigld** [everydayrails/rails-4-1-rspec-3-0#77]
I'm getting an error on this test at page 68. 
`spec/controllers/contacts_controller_spec.rb`
```
describe 'GET #index' do
...
context 'without params[:letter]' do
      it "populates an array of all contacts" do
        smith = create(:contact, lastname: 'Smith')
        jones = create(:contact, lastname: 'Jones')
        get :index
        expect(assigns(:contacts)).to match_array([smith, jones])
      end
...
```
my `contacts.rb`
```
FactoryGirl.define do
  factory :contact do
    firstname { Faker::Name.first_name }
    lastname { Faker::Name.last_name }
    email { Faker::Internet.email }

    after(:build) do |contact|
      [:home_phone, :work_phone, :mobile_phone].each do |phone|
        contact.phones << FactoryGirl.build(:phone,
          phone_type: phone,
          contact: contact
        )
      end
    end

    factory :invalid_contact do
      firstname nil
    end
  end
end
```

it's complaining these error:
```
Failures:

  1) ContactsController GET #index without params[:letter] populates an array of all contacts
     Failure/Error: expect(assigns(:contacts)).to match_array([smith, jones])
       expected collection contained:  [#<Contact id: 980190963, firstname: "Elza", lastname: "Smith", email: "kaley@pfeffer.net", created_at: "2017-04-18 23:47:46", updated_at: "2017-04-18 23:47:46">, #<Contact id: 980190964, firstname: "Charlie", lastname: "Jones", email: "cornelius_marks@bernier.net", created_at: "2017-04-18 23:47:46", updated_at: "2017-04-18 23:47:46">]
       actual collection contained:    [#<Contact id: 298486374, firstname: "MyString", lastname: "MyString", email: "MyString", created_at: "2017-04-13 18:21:39", updated_at: "2017-04-13 18:21:39">, #<Contact id: 980190962, firstname: "MyString", lastname: "MyString", email: "MyString", created_at: "2017-04-13 18:21:39", updated_at: "2017-04-13 18:21:39">, #<Contact id: 980190963, firstname: "Elza", lastname: "Smith", email: "kaley@pfeffer.net", created_at: "2017-04-18 23:47:46", updated_at: "2017-04-18 23:47:46">, #<Contact id: 980190964, firstname: "Charlie", lastname: "Jones", email: "cornelius_marks@bernier.net", created_at: "2017-04-18 23:47:46", updated_at: "2017-04-18 23:47:46">]
       the extra elements were:        [#<Contact id: 298486374, firstname: "MyString", lastname: "MyString", email: "MyString", created_at: "2017-04-13 18:21:39", updated_at: "2017-04-13 18:21:39">, #<Contact id: 980190962, firstname: "MyString", lastname: "MyString", email: "MyString", created_at: "2017-04-13 18:21:39", updated_at: "2017-04-13 18:21:39">]
     # ./spec/controllers/contacts_controller_spec.rb:39:in `block (4 levels) in <top (required)>'

Finished in 0.85604 seconds (files took 7.05 seconds to load)
14 examples, 1 failure

Failed examples:

rspec ./spec/controllers/contacts_controller_spec.rb:35 # ContactsController GET #index without params[:letter] populates an array of all contacts
```

**Comment by dimanyc** [comment]
This assertion is failing for two reasons:

1. both `smith` and `jones` are strings so your expectation must be something like:  ```expect(assigns(:contacts)).to match_array(['smith', 'jones'])```
2. Both, `lastname` and `firstname` should be capitalized since `Faker::Name` returns capitalized strings if I remember correctly.

**Comment by dimanyc** [comment]
It looks like `contact` instances are created elsewhere in your code, since `actual collection contained` includes other objects besides `smith` and `jones`. Your spec is failing because **`match_array` will will be true only if the array at hand contains the objects you specify and nothing else**. So:

```ruby
expect([1, 2, 3]).to     match_array([3, 2, 1]) # will return true
expect([1, 2, 3, 4]).to  match_array([3, 2, 1]) # will return false
```

You can either figure out where these additional instances are being created and clean them with something like [database_cleaner,](https://github.com/DatabaseCleaner/database_cleaner) or use `include` instead of `match array`:

```ruby
expect(assigns(:contacts)).to include(smith, jones)
```

**Comment by romenigld** [comment]
I'm following and typing the samples for a better recording. 
So I try to put like 'String' and then the sample include and was the same error.
So when I try many times I have a different error. And I don't know what is occurring maybe is something in the core of the RSpec. Try to config the database_cleaner. And this error persists:
```
$ git branch
  01_untested
  02_setup
  03_models
* 04_factories
  05_controller_basics
  master
$ rspec spec/controllers/contacts_controller_spec.rb§
/Users/romenigld/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.3/lib/rspec/core/configuration.rb:1105:in `load': cannot load such file -- /Users/romenigld/workspace/ebooks/everyday_rails_testing_with_rspec/rails-4-1-rspec-3-0/spec/controllers/contacts_controller_spec.rb§ (LoadError)
	from /Users/romenigld/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.3/lib/rspec/core/configuration.rb:1105:in `block in load_spec_files'
	from /Users/romenigld/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.3/lib/rspec/core/configuration.rb:1105:in `each'
	from /Users/romenigld/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.3/lib/rspec/core/configuration.rb:1105:in `load_spec_files'
	from /Users/romenigld/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.3/lib/rspec/core/runner.rb:96:in `setup'
	from /Users/romenigld/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.3/lib/rspec/core/runner.rb:84:in `run'
	from /Users/romenigld/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.3/lib/rspec/core/runner.rb:69:in `run'
	from /Users/romenigld/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.3/lib/rspec/core/runner.rb:37:in `invoke'
	from /Users/romenigld/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.3/exe/rspec:4:in `<top (required)>'
	from /Users/romenigld/.rvm/gems/ruby-2.1.1/bin/rspec:23:in `load'
	from /Users/romenigld/.rvm/gems/ruby-2.1.1/bin/rspec:23:in `<main>'
	from /Users/romenigld/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/romenigld/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by dimanyc** [comment]
Try adding a `before` block to remove all records of `contact` prior to creating `smith` and `jones`

```ruby
describe 'GET #index' do

  before(:each) do
    Contact.destroy_all
  end
...
context 'without params[:letter]' do
      it "populates an array of all contacts" do
        smith = create(:contact, lastname: 'Smith')
        jones = create(:contact, lastname: 'Jones')
        get :index
        expect(assigns(:contacts)).to match_array([smith, jones])
      end
...
```
As far as setting up database cleaner, use their [README Rspec example](https://github.com/DatabaseCleaner/database_cleaner#rspec-example). If you are still having issues, post a link to your repo here.

**Comment by romenigld** [comment]
It's complaining this error that I show you before. It's started of nowhere as I testing this problem, it's very strange. 
error:
```
rspec spec/controllers/contacts_controller_spec.rb§
/Users/romenigld/.rvm/gems/ruby-2.1.1/gems/rspec-core-3.1.3/lib/rspec/core/configuration.rb:1105:in `load': cannot load such file -- /Users/romenigld/workspace/ebooks/everyday_rails_testing_with_rspec/rails-4-1-rspec-3-0/spec/controllers/contacts_controller_spec.rb§ (LoadError)
```

**Comment by romenigld** [comment]
I do a fool commit and so I change the branch for the 05 chapter. Then the error persists. So I run the bundle install. And when I try the rspec command, the rspec command works. So i git checkout for the 04 chapter branch.
Do the same I run the bundle install. Then with your before block for delete_all. works fine!!
```
ContactsController
  GET #show
    assigns the requested contact to @contact
    renders the :show template
  GET #index
    with params[:letter]
      populates an array of contacts starting with the letter
      renders the :index template
    without params[:letter]
      populates an array of all contacts
      renders the :index template
  GET #new
    assigns a new Contact to @contact
    renders the :new template
  GET #edit
    assigns the requested contact to @contact
    renders the :edit template
  POST #create
    with valid attributes
      saves the new contact in the database
      redirects to contacts#show
    with invalid attrubutes
      does not save the new contact in the database
      re-renders the :new template

Finished in 0.60853 seconds (files took 2.32 seconds to load)
14 examples, 0 failures
```
So I will continue the ebook. Thank's for reply!!

**Comment by ruralocity** [comment]
Hey @dimanyc, thanks for helping out here!
